### ISSUE TITLE
How is the status of the project?

### ISSUE THREAD

**Issue by GPrimola** [davidstump/slackex#8]
Hey guys,

I'd like to know the status of the project, is it finished?
Can I help it somehow?
I'd like to use it, I don't know if I start with this one or with https://github.com/BlakeWilliams/Elixir-Slack?

**Comment by davidstump** [comment]
Howdy!

While I always welcome PRs, looking at the commit history I would definitely say Elixir-Slack looks like a much newer/better alternative.

Thanks,
David
